apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - name: api-server
        image: {{ include "api-server.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        volumeMounts:
        - name: app-config
          mountPath: /app
      volumes:
      - name: app-config
        secret:
          secretName: {{ .Release.Name }}
          optional: true
