apiVersion: v2
appVersion: "1.0.0"
name: api-server
description: A Helm chart for prework
kubeVersion: ">= 1.21.0-0"
version: 0.1.0
maintainers:
- name: xinyan
  email: yan740487738@gmail.com
dependencies:
- name: nginx-ingress
  repository: file://charts/nginx-ingress
  version: 0.16.0
  condition: subnginx.enabled
- name: mysql
  repository: file://charts/mysql
  version: 0.1.0
  condition: submysql.enabled
